### ISSUE TITLE
cluster-sentinel example cannot be configured for several masters in cluster

### ISSUE THREAD

**Issue by ybonda** [spring-projects/spring-data-examples#166]
The example of cluster-sentinel works only if cluster contains only one single master node.
Is there any possibility to configure it for 3 masters?

**Comment by mp911de** [comment]
Hi @ybonda,
the name "cluster-sentinel" is a bit misleading. It's related to Redis Sentinel-only. While you can configure Redis Sentinel monitoring multiple masters, one `RedisConnectionFactory` uses only one master name per instance. If you want to open connections to multiple master nodes using Redis Sentinel, you require multiple `RedisConnectionFactory` instances.

If you mean Redis Cluster, see  the [`cluster`](https://github.com/spring-projects/spring-data-examples/tree/master/redis/cluster) example.

**Comment by olivergierke** [comment]
Shall we rename the module then?

**Comment by mp911de** [comment]
I'll take care of it.

**Comment by ybonda** [comment]
But how is possible for a developer to use jedis spring data for cluster without care about failing nodes?

In [cluster](https://github.com/spring-projects/spring-data-examples/tree/master/redis/cluster) example I configured spring for 6 nodes (3 masters. 3 slaves). But if one of the masters is down then jedis template fails with exception. 

org.junit.AssumptionViolatedException: 
Seems as redis is not running at 172.31.150.113:7000.
	at example.springdata.redis.test.util.RequiresRedisServer.before(RequiresRedisServer.java:49)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at example.springdata.redis.test.util.RequiresRedisServer.before(RequiresRedisServer.java:47)
	... 10 more

Can you please explain what should I do in order to ensure that redis template will still work even if one master failed (of course it's slave became a master)?

**Comment by mp911de** [comment]
We have to untangle things here. The examples are feature showcases and require a certain setup to run. Fault-tolerancy for Spring Data Redis is a different topic though.

This repo is not to intended for general discussions but for simple examples. If you feel the urge to continue the discussion, then [StackOverflow](https://stackoverflow.com/questions/tagged/spring-data-redis) is a great place or, if you have ideas how to improve Spring Data Redis or you want to report a bug, then create a ticket in our [Jira](https://jira.spring.io/browse/DATAREDIS).

**Comment by mp911de** [comment]
Closing this ticket as the renaming issue is resolved for us.
