### ISSUE TITLE
Jedis template fails if one of the nodes is down in redis-cluster example

### ISSUE THREAD

**Issue by ybonda** [spring-projects/spring-data-examples#168]
How possible for a developer to use jedis spring data for cluster without care about failing nodes?

In cluster example I configured spring for 6 nodes (3 masters. 3 slaves). But if one of the masters is down then jedis template fails with exception.

org.junit.AssumptionViolatedException: 
Seems as redis is not running at 172.31.150.113:7000.
at example.springdata.redis.test.util.RequiresRedisServer.before(RequiresRedisServer.java:49)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.net.SocketTimeoutException: connect timed out
at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at example.springdata.redis.test.util.RequiresRedisServer.before(RequiresRedisServer.java:47)
... 10 more

Can you please explain what should I do in order to ensure that redis template will still work even if one master failed (of course it's slave became a master)?

**Comment by mp911de** [comment]
Closing this ticket in favor of #166.
