### ISSUE TITLE
mongodb projection results in MappingInstantiationException

### ISSUE THREAD

**Issue by kevcgrant** [spring-projects/spring-data-examples#191]
I am attempting to follow the [MongoDB Projections](https://github.com/spring-projects/spring-data-examples/blob/master/mongodb/example/src/main/java/example/springdata/mongodb/projections/CustomerRepository.java) example for a User class and repository, with these relevant files:
**User.java**
```java
// ... imports
@Getter
@Setter
public class User {

    @Id 
    @Setter(AccessLevel.NONE)
    @Getter(AccessLevel.NONE)
    private String id;

    @JsonProperty ("id")
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private String userId;

    private String name;
    private String imageUrl;
    private ArrayList<Friend> friends;
    private ArrayList<Friend> incomingRequests;

    public String getUserId() {
        return id;
    }

   // ... Other fields / methods
}
```

**UserProjection.java**
```java
interface UserProjection {
    String getName();
    String getId();
    String getImageUrl();
}
```

**UserRepository.java**
```java
@RepositoryRestResource(collectionResourceRel = "users", path = "users")
public interface UserRepository extends MongoRepository<User, String> {

	List<UserProjection> findAllProjectedBy();

    // ...
}
```

**build.gradle**
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:1.3.5.RELEASE")
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'spring-boot'

jar {
    baseName = 'gs-accessing-mongodb-data-rest'
    version =  '0.1.0'
}

repositories {
    mavenCentral()
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
    compile("org.springframework.boot:spring-boot-starter-data-rest")
    compile("org.springframework.boot:spring-boot-starter-data-mongodb")
    compile group: 'org.springframework.data', name: 'spring-data-jpa', version: '1.10.1.RELEASE'
    compile group: 'org.projectlombok', name: 'lombok', version: '1.16.8'
    testCompile("junit:junit")
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.3'
}

```

However, when I try to make a call to `localhost:8080/users/search/findAllProjectedBy`, this is the response:
```json
{
  "timestamp": 1464282078189,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.springframework.data.mapping.model.MappingInstantiationException",
  "message": "Failed to instantiate hello.user.UserProjection using constructor NO_CONSTRUCTOR with arguments ",
  "path": "/users/search/findAllProjectedBy"
}
```

And in the logs, it states `org.springframework.beans.BeanInstantiationException: Failed to instantiate [hello.user.UserProjection]: Specified class is an interface`:
```
org.springframework.beans.BeanInstantiationException: Failed to instantiate [hello.user.UserProjection]: Specified class is an interface
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:101) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.data.convert.ReflectionEntityInstantiator.createInstance(ReflectionEntityInstantiator.java:61) ~[spring-data-commons-1.11.2.RELEASE.jar!/:na]
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:83) ~[spring-data-commons-1.11.2.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:251) ~[spring-data-mongodb-1.8.2.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:231) ~[spring-data-mongodb-1.8.2.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:191) ~[spring-data-mongodb-1.8.2.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:187) ~[spring-data-mongodb-1.8.2.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:78) ~[spring-data-mongodb-1.8.2.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate$ReadDbObjectCallback.doWith(MongoTemplate.java:2224) ~[spring-data-mongodb-1.8.2.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1900) ~[spring-data-mongodb-1.8.2.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1723) ~[spring-data-mongodb-1.8.2.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1706) ~[spring-data-mongodb-1.8.2.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:602) ~[spring-data-mongodb-1.8.2.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery$Execution.readCollection(AbstractMongoQuery.java:170) ~[spring-data-mongodb-1.8.2.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery$CollectionExecution.execute(AbstractMongoQuery.java:193) ~[spring-data-mongodb-1.8.2.RELEASE.jar!/:na]
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:104) ~[spring-data-mongodb-1.8.2.RELEASE.jar!/:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:462) ~[spring-data-commons-1.11.2.RELEASE.jar!/:na]
```

**Comment by olivergierke** [comment]
You're using Spring Boot 1.3.5 which is not on Hopper and thus doesn't include the projection feature on the repository level yet.

**Comment by kevcgrant** [comment]
Ah. Thank you.
