### ISSUE TITLE
Unit test FAILED in selectProjections()

### ISSUE THREAD

**Issue by annbigbig** [spring-projects/spring-data-examples#208]
thanks for all of developers for this great project,
this project is so huge for me (project then nested serveral sub-projects)
so for simplicity I have copy/paste the source code from here,
and make it another my own version,
everytime I tried to build the project, it will throw Exception
from class CassandraOperationsIntegrationTests.selectProjections()

situation 1
```
	@Test
	@SuppressWarnings("unchecked")
	public void selectProjections() {

		User user = new User();
		user.setId(42L);
		user.setUsername("heisenberg");
		user.setFirstname("Walter");
		user.setLastname("White");

		template.insert(user);

		Long id = template.selectOne(QueryBuilder.select("user_id").from("users"), Long.class);
		assertThat(id, is(user.getId()));
       }
```

it will cause the following ERROR

```
04:05:05.902 [DEBUG] [TestEventLogger] com.kashu.demo.CassandraOperationsIntegrationTests > selectProjections STARTED
04:05:06.409 [DEBUG] [TestEventLogger]
04:05:06.409 [DEBUG] [TestEventLogger] com.kashu.demo.CassandraOperationsIntegrationTests > selectProjections FAILED
04:05:06.410 [DEBUG] [TestEventLogger]     org.springframework.data.mapping.model.MappingException: No mapping metadata found for java.lang.Long
04:05:06.410 [DEBUG] [TestEventLogger]         at org.springframework.data.cassandra.convert.MappingCassandraConverter.readRow(MappingCassandraConverter.java:112)
04:05:06.410 [DEBUG] [TestEventLogger]         at org.springframework.data.cassandra.convert.MappingCassandraConverter.read(MappingCassandraConverter.java:200)
04:05:06.410 [DEBUG] [TestEventLogger]         at org.springframework.data.cassandra.core.CassandraConverterRowCallback.doWith(CassandraConverterRowCallback.java:47)
04:05:06.410 [DEBUG] [TestEventLogger]         at org.springframework.data.cassandra.core.CassandraTemplate.selectOne(CassandraTemplate.java:624)
04:05:06.410 [DEBUG] [TestEventLogger]         at org.springframework.data.cassandra.core.CassandraTemplate.selectOne(CassandraTemplate.java:469)
04:05:06.410 [DEBUG] [TestEventLogger]         at com.kashu.demo.CassandraOperationsIntegrationTests.selectProjections(CassandraOperationsIntegrationTests.java:135)
04:05:06.410 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04:05:06.410 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
04:05:06.410 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:05:06.410 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
04:05:06.410 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
04:05:06.410 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
04:05:06.410 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
04:05:06.410 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
04:05:06.411 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
04:05:06.412 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
04:05:06.412 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04:05:06.412 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
04:05:06.412 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:05:06.412 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
04:05:06.412 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
04:05:06.412 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
04:05:06.412 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
04:05:06.412 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
04:05:06.412 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
04:05:06.412 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
04:05:06.412 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04:05:06.412 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
04:05:06.412 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:05:06.412 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
04:05:06.412 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
04:05:06.412 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
04:05:06.412 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
04:05:06.412 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
04:05:06.412 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
04:05:06.412 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
04:05:06.413 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
04:05:06.413 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:745)
```

situation 2

```
	@Test
	@SuppressWarnings("unchecked")
	public void selectProjections() {

		User user = new User();
		user.setId(42L);
		user.setUsername("heisenberg");
		user.setFirstname("Walter");
		user.setLastname("White");

		template.insert(user);

		Map<String, Object> map = template.selectOne(QueryBuilder.select().from("users"), Map.class);
		assertThat(map, hasEntry("user_id", user.getId()));
		assertThat(map, hasEntry("fname", "Walter"));
       }
```

and it will cause the following ERROR

```
04:01:51.306 [DEBUG] [TestEventLogger] com.kashu.demo.CassandraOperationsIntegrationTests > selectProjections STARTED
04:01:51.771 [DEBUG] [TestEventLogger]
04:01:51.772 [DEBUG] [TestEventLogger] com.kashu.demo.CassandraOperationsIntegrationTests > selectProjections FAILED
04:01:51.773 [DEBUG] [TestEventLogger]     org.springframework.data.cassandra.mapping.VerifierMappingExceptions: java.util.Map:
04:01:51.773 [DEBUG] [TestEventLogger]     Cassandra entities must have the @Table, @Persistent or @PrimaryKeyClass Annotation
04:01:51.773 [DEBUG] [TestEventLogger]         at org.springframework.data.cassandra.mapping.BasicCassandraPersistentEntityMetadataVerifier.verify(BasicCassandraPersistentEntityMetadataVerifier.java:45)
04:01:51.773 [DEBUG] [TestEventLogger]         at org.springframework.data.cassandra.mapping.BasicCassandraPersistentEntity.verify(BasicCassandraPersistentEntity.java:198)
04:01:51.773 [DEBUG] [TestEventLogger]         at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:327)
04:01:51.773 [DEBUG] [TestEventLogger]         at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:180)
04:01:51.774 [DEBUG] [TestEventLogger]         at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:67)
04:01:51.774 [DEBUG] [TestEventLogger]         at org.springframework.data.cassandra.convert.MappingCassandraConverter.readRow(MappingCassandraConverter.java:110)
04:01:51.774 [DEBUG] [TestEventLogger]         at org.springframework.data.cassandra.convert.MappingCassandraConverter.read(MappingCassandraConverter.java:200)
04:01:51.774 [DEBUG] [TestEventLogger]         at org.springframework.data.cassandra.core.CassandraConverterRowCallback.doWith(CassandraConverterRowCallback.java:47)
04:01:51.775 [DEBUG] [TestEventLogger]         at org.springframework.data.cassandra.core.CassandraTemplate.selectOne(CassandraTemplate.java:624)
04:01:51.775 [DEBUG] [TestEventLogger]         at org.springframework.data.cassandra.core.CassandraTemplate.selectOne(CassandraTemplate.java:469)
04:01:51.775 [DEBUG] [TestEventLogger]         at com.kashu.demo.CassandraOperationsIntegrationTests.selectProjections(CassandraOperationsIntegrationTests.java:141)
04:01:51.775 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04:01:51.775 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
04:01:51.776 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:01:51.776 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
04:01:51.776 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
04:01:51.776 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
04:01:51.776 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
04:01:51.777 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
04:01:51.777 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
04:01:51.777 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
04:01:51.777 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
04:01:51.778 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
04:01:51.778 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
04:01:51.779 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
04:01:51.779 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
04:01:51.779 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
04:01:51.779 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
04:01:51.779 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
04:01:51.780 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
04:01:51.780 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
04:01:51.780 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
04:01:51.780 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
04:01:51.780 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
04:01:51.781 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
04:01:51.781 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
04:01:51.781 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
04:01:51.781 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
04:01:51.781 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
04:01:51.782 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04:01:51.782 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
04:01:51.782 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:01:51.782 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
04:01:51.782 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
04:01:51.782 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
04:01:51.783 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
04:01:51.783 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
04:01:51.783 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
04:01:51.783 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
04:01:51.783 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04:01:51.784 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
04:01:51.784 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:01:51.786 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
04:01:51.786 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
04:01:51.786 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
04:01:51.787 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
04:01:51.787 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
04:01:51.787 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
04:01:51.787 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
04:01:51.787 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
04:01:51.788 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:745)
```

summary : 
in situation 1, selectProjections() will throw org.springframework.data.mapping.model.MappingException: No mapping metadata found for java.lang.Long

in situation 2 , selectProjections() will throw
org.springframework.data.cassandra.mapping.VerifierMappingExceptions: java.util.Map:
Cassandra entities must have the @Table, @Persistent or @PrimaryKeyClass Annotation

so how should I prevent these two Exceptions been thrown from function selectProjections()?
why these 2 Exceptions will be thrown?
May I do something for fixing them ? how to do that?
any suggestion will be appreciated.

**Comment by mp911de** [comment]
Please make sure to use the `Ingalls-M1` release, see the [Ingalls M1 announcement](https://spring.io/blog/2016/07/27/spring-data-release-train-ingalls-m1-released) for further details. 

If you have questions, please use StackOverflow as this is not a general discussion forum.
