### ISSUE TITLE
Persist a List<String> with spring data jpa

### ISSUE THREAD

**Issue by berrytchaks** [spring-projects/spring-data-examples#225]
Hi Everyone,

I working on the refactoring of a code. Basically I have to migrate a project using the dependency of the [cassandra driver](https://mvnrepository.com/artifact/com.datastax.cassandra/cassandra-driver-mapping/3.1.2) to the dependency of an [embedded h2 database](https://mvnrepository.com/artifact/com.h2database/h2/1.4.193). I have refactored most of the code and when I launch the code have an exception.

    Caused by: org.hibernate.MappingException: Could not determine type for: java.util.List, at table: mytable, for columns: [org.hibernate.mapping.Column(containers)]

Here is my code

    import java.util.List;
    import javax.persistence.Column;
    import javax.persistence.Entity;
    import javax.persistence.EntityListeners;
    import javax.persistence.GeneratedValue;
    import javax.persistence.Id;
    import org.springframework.data.jpa.domain.support.AuditingEntityListener;
    @Entity
    @EntityListeners(AuditingEntityListener.class)
    public class Mytable {
	@Id
	private String id;
	
	@Column
	private String name;
	
	@Column
	private List<String> containers;
     }

I using spring boot in my application. The pom have the following dependencies.

       <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.4.2.RELEASE</version>
		<relativePath /> 
	</parent>
        <profiles>
		<profile>
			<id>local</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<properties>
		           <spring.datasource.driverClassName>org.h2.Driver</spring.datasource.driverClassName>
				<spring.datasource.url>jdbc:h2:file:~/testdb</spring.datasource.url>
				<spring.datasource.username>sa</spring.datasource.username>
				<spring.datasource.password>sa</spring.datasource.password>
				<spring.jpa.database>h2</spring.jpa.database>
				<spring.datasource.platform>h2</spring.datasource.platform>
				<spring.jpa.show-sql>true</spring.jpa.show-sql>
				<spring.jpa.hibernate.ddl-auto>create-drop</spring.jpa.hibernate.ddl-auto>
			</properties>
		</profile>
        </profiles>
        <dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
			<version>1.4.2.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
			<version>1.4.191</version>
		</dependency>
         ....
         </dependencies>

After launching this code, I have the following stacktrace

     org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1081)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:856)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at com.wouri.app.Application.main(Application.java:28)
     Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:954)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:882)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:353)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:373)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:362)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579)
	... 16 common frames omitted
Caused by: org.hibernate.MappingException: Could not determine type for: java.util.List, at table: mytable, for columns: [org.hibernate.mapping.Column(containers)]
	at org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:431)
	at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:398)
	at org.hibernate.mapping.Property.isValid(Property.java:225)
	at org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:595)
	at org.hibernate.mapping.RootClass.validate(RootClass.java:265)
	at org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:329)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:443)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:879)
	... 22 common frames omitted

Any Clues please.
Thanks.

**Comment by olivergierke** [comment]
Please use StackOverflow for general usage questions. Collections of primitive types have to be mapped using JPA's `@ElementCollection`. Please refer to the JPA spec, Hibernate documentation for details.

**Comment by berrytchaks** [comment]
@olivergierke Thanks for the reply. Sorry but I have tried **@ElementCollection** but it giving some exception. Anyway I will post on StackOverflow. Sorry for the inconvenience.
