### ISSUE TITLE
Demonstrate use of @DataJpaTest when multiple datasources are configured

### ISSUE THREAD

**Issue by bemace** [spring-projects/spring-data-examples#332]
I've successfully configured two datasources per your example, but it appears additional configuration is needed to make @DataJpaTest's magic work. Currently my attempts fail with below stack trace, and it's not at all clear to a beginner what needs to change to make this work.

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean]: Factory method 'mainEntityManager' threw exception; nested exception is java.lang.IllegalArgumentException: No visible constructors in class org.springframework.boot.test.autoconfigure.jdbc.TestDatabaseAutoConfiguration$EmbeddedDataSourceFactoryBean
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 66 more
Caused by: java.lang.IllegalArgumentException: No visible constructors in class org.springframework.boot.test.autoconfigure.jdbc.TestDatabaseAutoConfiguration$EmbeddedDataSourceFactoryBean
	at org.springframework.cglib.proxy.Enhancer.filterConstructors(Enhancer.java:666)
	at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:567)
	at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)

```

**Comment by olivergierke** [comment]
I guess you need to bring this up with the Boot team. I am not sure `@DataJpaTest` is designed to work with multiple DataSources.

**Comment by viniciusffj** [comment]
Hi @bemace 
Did you find any solution for your problem? 
If yes, can you share it? I am facing a similar issue.

**Comment by maciejp** [comment]
@bemace , @viniciusffj did you solve it? I have the same issue with _@JdbcTest_ .

**Comment by gubespam** [comment]
Found a possible solution [here][1].

Basically you manually configure the H2 database appropriately instead of letting Spring do it automatically.

Create an application.properties file in “src/test/resources” with the following content

    # Let Spring autodetect the different SQL Dialects of each datasource
    spring.jpa.database=default
    # Generate the DB schema in the In-Memory H2 databases based on the JPA Entities
    spring.jpa.generate-ddl=true
    
    # H2 In-Memory Database "foo" (used in tests instead of a real PostgreSQL DB)
    spring.datasource.url=jdbc:h2:mem:foo;DB_CLOSE_ON_EXIT=FALSE
    spring.datasource.username=sa
    spring.datasource.password=
    spring.datasource.driver-class-name=org.h2.Driver
    
    # H2 In-Memory Database "bar" (used in tests instead of a real PostgreSQL DB)
    bar.datasource.url=jdbc:h2:mem:bar;DB_CLOSE_ON_EXIT=FALSE
    bar.datasource.username=sa
    bar.datasource.password=
    bar.datasource.driver-class-name=org.h2.Driver


  [1]: https://medium.com/@joeclever/integration-testing-multiple-datasources-in-spring-boot-and-spring-data-with-spock-f88e1428ce9f

**Comment by sddakoty** [comment]
I'm having the same problem when multiple datasources are configured (and only using `@AutoConfigureTestDatabase` annotation instead of `@DataJpaTest`, which uses it internally).

I could also solve it by overriding the application.properties database config with H2 settings manually.
But I'd also prefer spring to detect all DS and replace them with H2 embedded automatically. That's what the `@AutoConfigureTestDatabase` is for!

**Comment by membersound** [comment]
As I run into that issue again today, sadly there has not been any action on this issue. Could you maybe have a look at it again, and evaluate if it could be fixed or suggested workarounds could be added?

**Comment by odrotbohm** [comment]
This the issue tracker for the examples, not one for the individual projects. As indicated [before](https://github.com/spring-projects/spring-data-examples/issues/332#issuecomment-358696590), this seems to be related to the way `@DataJpaTests` are desigend to work in Boot, i.e. it might make sense to rather reach out to the Boot team.
