### ISSUE TITLE
how to run the examples

### ISSUE THREAD

**Issue by jingchh** [spring-projects/spring-data-examples#369]
could u give a software version list to run the example, and give some simple example from the shallower to the deeper? ths
java -version
eclipse, sts or other
ths

**Comment by schauder** [comment]
All the examples form a tree of maven projects. And they are JUnit tests, so you can run them by executing. 

    mvn clean test

Some might need a matching datastore running. See the `travis.yml` file in the root directory for details.

The requirement of Spring Data is currently Java 8, so that's the baseline for the examples as well.

**Comment by jingchh** [comment]
let me try

**Comment by jingchh** [comment]
......................
[INFO] Spring Data MongoDB - Example Utilities ............ SUCCESS [  2.561 s]
[INFO] Spring Data MongoDB - Change Streams ............... FAILURE [  9.963 s]
[INFO] Spring Data MongoDB - Example ...................... SKIPPED
 ......................

2018-05-29 21:41:54,577  INFO le.springdata.mongodb.util.EmbeddedMongo: 306 - Starting replica set 'rs0' servers at ports 58886,58891,58902
2018-05-29 21:41:57,336 ERROR flapdoodle.embed.process.runtime.Starter:  68 - prepare executable
java.io.IOException: Could not open inputStream for https://downloads.mongodb.org/win32/mongodb-win32-x86_64-ssl-3.7.9.zip
        at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:131)
        at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:69)

Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://downloads.mongodb.org/win32/mongodb-win32-x86_64-ssl-3.7.
9.zip
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)

**i use mvn compile it, some projects success,some project failed.**

**i want know how to compile it with eclipse/idea/sts edit it. but it failed at all ide.
could u help me to give a detailed methods, ths.**

_i tried to import the maven projects to eclipse and idea,but compile failed too.
i had theck the jdk that is 1.8
but what happened to my env,help me.
my pc is windows10, jdk is 1.8, idea is 2017.2.2 eclipseSTS is 3.7.3_
