### ISSUE TITLE
MongoSocketOpenException occurs when running spring-data-mongodb reactive test

### ISSUE THREAD

**Issue by hopefulwalker** [spring-projects/spring-data-examples#451]
When I running the spring sub project: spring-data-examples-master\mongodb\reactive, The following exceptions occurs。I'ms using spring boot version : 2.1.3.RELEASE
```
19:15:47.493 [main] DEBUG org.springframework.test.context.junit4.SpringJUnit4ClassRunner - SpringJUnit4ClassRunner constructor called with [class example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]
19:15:47.510 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating CacheAwareContextLoaderDelegate from class [org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate]
19:15:47.518 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating BootstrapContext using constructor [public org.springframework.test.context.support.DefaultBootstrapContext(java.lang.Class,org.springframework.test.context.CacheAwareContextLoaderDelegate)]
19:15:47.535 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating TestContextBootstrapper for test class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest] from class [org.springframework.boot.test.context.SpringBootTestContextBootstrapper]
19:15:47.547 [main] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Neither @ContextConfiguration nor @ContextHierarchy found for test class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest], using SpringBootContextLoader
19:15:47.550 [main] DEBUG org.springframework.test.context.support.AbstractContextLoader - Did not detect default resource location for test class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]: class path resource [example/springdata/mongodb/people/ReactiveMongoTemplateIntegrationTest-context.xml] does not exist
19:15:47.550 [main] DEBUG org.springframework.test.context.support.AbstractContextLoader - Did not detect default resource location for test class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]: class path resource [example/springdata/mongodb/people/ReactiveMongoTemplateIntegrationTestContext.groovy] does not exist
19:15:47.550 [main] INFO org.springframework.test.context.support.AbstractContextLoader - Could not detect default resource locations for test class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]: no resource found for suffixes {-context.xml, Context.groovy}.
19:15:47.551 [main] INFO org.springframework.test.context.support.AnnotationConfigContextLoaderUtils - Could not detect default configuration classes for test class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]: ReactiveMongoTemplateIntegrationTest does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
19:15:47.587 [main] DEBUG org.springframework.test.context.support.ActiveProfilesUtils - Could not find an 'annotation declaring class' for annotation type [org.springframework.test.context.ActiveProfiles] and class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]
19:15:47.672 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [D:\works\learning\spring-data\reactive\out\production\classes\example\springdata\mongodb\people\ApplicationConfiguration.class]
19:15:47.682 [main] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Found @SpringBootConfiguration example.springdata.mongodb.people.ApplicationConfiguration for test class example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest
19:15:47.784 [main] DEBUG org.springframework.boot.test.context.SpringBootTestContextBootstrapper - @TestExecutionListeners is not present for class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]: using defaults.
19:15:47.785 [main] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener]
19:15:47.792 [main] DEBUG org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Skipping candidate TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener] due to a missing dependency. Specify custom listener classes or make the default listener classes and their required dependencies available. Offending class: [javax/servlet/ServletContext]
19:15:47.801 [main] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Using TestExecutionListeners: [org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@35ef1869, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@c33b74f, org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@130161f7, org.springframework.test.context.support.DirtiesContextTestExecutionListener@2c767a52, org.springframework.test.context.transaction.TransactionalTestExecutionListener@619713e5, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener@708f5957, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@68999068, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@7722c3c3, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@2ef3eef9, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@243c4f91, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@291ae]
19:15:47.804 [main] DEBUG org.springframework.test.annotation.ProfileValueUtils - Retrieved @ProfileValueSourceConfiguration [null] for test class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]
19:15:47.807 [main] DEBUG org.springframework.test.annotation.ProfileValueUtils - Retrieved ProfileValueSource type [class org.springframework.test.annotation.SystemProfileValueSource] for class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]19:15:47.845 [main] DEBUG org.springframework.test.annotation.ProfileValueUtils - Retrieved @ProfileValueSourceConfiguration [null] for test class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]
19:15:47.845 [main] DEBUG org.springframework.test.annotation.ProfileValueUtils - Retrieved ProfileValueSource type [class org.springframework.test.annotation.SystemProfileValueSource] for class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]19:15:47.846 [main] DEBUG org.springframework.test.annotation.ProfileValueUtils - Retrieved @ProfileValueSourceConfiguration [null] for test class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]
19:15:47.848 [main] DEBUG org.springframework.test.annotation.ProfileValueUtils - Retrieved ProfileValueSource type [class org.springframework.test.annotation.SystemProfileValueSource] for class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]
19:15:47.849 [main] DEBUG org.springframework.test.annotation.ProfileValueUtils - Retrieved @ProfileValueSourceConfiguration [null] for test class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]
19:15:47.849 [main] DEBUG org.springframework.test.annotation.ProfileValueUtils - Retrieved ProfileValueSource type [class org.springframework.test.annotation.SystemProfileValueSource] for class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]
19:15:47.853 [main] DEBUG org.springframework.test.context.support.AbstractDirtiesContextTestExecutionListener - Before test class: context [DefaultTestContext@661972b0 testClass = ReactiveMongoTemplateIntegrationTest, testInstance = [null], testMethod = [null], testException = [null], mergedContextConfiguration = [MergedContextConfiguration@5af3afd9 testClass = ReactiveMongoTemplateIntegrationTest, locations = '{}', classes = '{class example.springdata.mongodb.people.ApplicationConfiguration}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@26aa12dd, org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@d44fc21, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@4e7dc304, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@536aaa8d], contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map[[empty]]], class annotated with @DirtiesContext [false] with mode [null].
19:15:47.854 [main] DEBUG org.springframework.test.annotation.ProfileValueUtils - Retrieved @ProfileValueSourceConfiguration [null] for test class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]
19:15:47.854 [main] DEBUG org.springframework.test.annotation.ProfileValueUtils - Retrieved ProfileValueSource type [class org.springframework.test.annotation.SystemProfileValueSource] for class [example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest]
19:15:47.858 [main] DEBUG org.springframework.test.context.support.DependencyInjectionTestExecutionListener - Performing dependency injection for test context [[DefaultTestContext@661972b0 testClass = ReactiveMongoTemplateIntegrationTest, testInstance = example.springdata.mongodb.people.ReactiveMongoTemplateIntegrationTest@12468a38, testMethod = [null], testException = [null], mergedContextConfiguration = [MergedContextConfiguration@5af3afd9 testClass = ReactiveMongoTemplateIntegrationTest, locations = '{}', classes = '{class example.springdata.mongodb.people.ApplicationConfiguration}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@26aa12dd, org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@d44fc21, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@4e7dc304, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@536aaa8d], contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map[[empty]]]].
19:15:47.885 [main] DEBUG org.springframework.test.context.support.TestPropertySourceUtils - Adding inlined properties to environment: {spring.jmx.enabled=false, org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true, server.port=-1}

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.3.RELEASE)

2019-02-28 19:15:48.187  INFO 23556 --- [           main] m.p.ReactiveMongoTemplateIntegrationTest : Starting ReactiveMongoTemplateIntegrationTest on HSZ-P1148 with PID 23556 (started by Walker.Zhang in D:\works\learning\spring-data\reactive)
2019-02-28 19:15:48.188  INFO 23556 --- [           main] m.p.ReactiveMongoTemplateIntegrationTest : No active profile set, falling back to default profiles: default
2019-02-28 19:15:48.607  INFO 23556 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-02-28 19:15:48.888  INFO 23556 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 277ms. Found 2 repository interfaces.
2019-02-28 19:15:48.894  INFO 23556 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-02-28 19:15:48.899  INFO 23556 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 5ms. Found 0 repository interfaces.
2019-02-28 19:15:49.763  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : note: noprealloc may hurt performance in many applications
2019-02-28 19:15:50.011  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.010+0800 I CONTROL  [initandlisten] MongoDB starting : pid=27568 port=52756 dbpath=C:\Users\WALKER~1.ZHA\AppData\Local\Temp\embedmongo-db-a1ba27d1-e91d-4990-9ab4-0d617e0bee06 64-bit host=HSZ-P1148
2019-02-28 19:15:50.011  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.011+0800 I CONTROL  [initandlisten] targetMinOS: Windows Vista/Windows Server 2008
2019-02-28 19:15:50.011  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.011+0800 I CONTROL  [initandlisten] db version v3.5.5
2019-02-28 19:15:50.011  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.011+0800 I CONTROL  [initandlisten] git version: 98515c812b6fa893613f063dae568ff8319cbfbd
2019-02-28 19:15:50.012  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.011+0800 I CONTROL  [initandlisten] allocator: tcmalloc
2019-02-28 19:15:50.012  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.011+0800 I CONTROL  [initandlisten] modules: none
2019-02-28 19:15:50.012  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.011+0800 I CONTROL  [initandlisten] build environment:
2019-02-28 19:15:50.012  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.011+0800 I CONTROL  [initandlisten]     distarch: x86_64
2019-02-28 19:15:50.012  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.011+0800 I CONTROL  [initandlisten]     target_arch: x86_64
2019-02-28 19:15:50.012  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.011+0800 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1", http: { enabled: false }, port: 52756 }, security: { authorization: "disabled" }, storage: { dbPath: "C:\Users\WALKER~1.ZHA\AppData\Local\Temp\embedmongo-db-a1ba27d1-e91d-4990-9ab4-0d617e0bee06", journal: { enabled: false }, mmapv1: { preallocDataFiles: false, smallFiles: true }, syncPeriodSecs: 0.0 } }
2019-02-28 19:15:50.012  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.013+0800 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7641M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=0,log_size=2GB),statistics_log=(wait=0),verbose=(recovery_progress),,log=(enabled=false),
2019-02-28 19:15:50.431  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.431+0800 W STORAGE  [initandlisten] Detected configuration for non-active storage engine mmapv1 when current storage engine is wiredTiger
2019-02-28 19:15:50.432  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.431+0800 I CONTROL  [initandlisten] 
2019-02-28 19:15:50.432  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.431+0800 I CONTROL  [initandlisten] ** NOTE: This is a development version (3.5.5) of MongoDB.
2019-02-28 19:15:50.432  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.431+0800 I CONTROL  [initandlisten] **       Not recommended for production.
2019-02-28 19:15:50.432  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:50.431+0800 I CONTROL  [initandlisten] 
2019-02-28 19:15:51.007  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:51.007+0800 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory 'C:/Users/WALKER~1.ZHA/AppData/Local/Temp/embedmongo-db-a1ba27d1-e91d-4990-9ab4-0d617e0bee06/diagnostic.data'
2019-02-28 19:15:51.274  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:51.275+0800 I INDEX    [initandlisten] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
2019-02-28 19:15:51.275  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:51.275+0800 I INDEX    [initandlisten] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2019-02-28 19:15:51.283  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:51.284+0800 I INDEX    [initandlisten] build index done.  scanned 0 total records. 0 secs
2019-02-28 19:15:51.287  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:51.288+0800 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.4
2019-02-28 19:15:51.288  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:51.289+0800 I NETWORK  [thread1] waiting for connections on port 52756
2019-02-28 19:15:51.288  INFO 23556 --- [           main] d.f.embed.mongo.MongodExecutable         : start de.flapdoodle.embed.mongo.config.MongodConfigBuilder$ImmutableMongodConfig@1efdcd5
2019-02-28 19:15:51.573  INFO 23556 --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:52756], mode=MULTIPLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-02-28 19:15:51.573  INFO 23556 --- [           main] org.mongodb.driver.cluster               : Adding discovered server localhost:52756 to client view of cluster
2019-02-28 19:15:51.612  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:51.613+0800 I NETWORK  [thread1] connection accepted from 127.0.0.1:52761 #1 (1 connection now open)
2019-02-28 19:15:51.620  INFO 23556 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-02-28T19:15:51.620+0800 I NETWORK  [conn1] received client metadata from 127.0.0.1:52761 conn1: { driver: { name: "mongo-java-driver", version: "3.8.2" }, os: { type: "Windows", name: "Windows 10", architecture: "amd64", version: "10.0" }, platform: "Java/Oracle Corporation/1.8.0_131-b11" }
2019-02-28 19:15:51.642  INFO 23556 --- [localhost:52756] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:1}] to localhost:52756
2019-02-28 19:15:51.645  INFO 23556 --- [localhost:52756] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=localhost:52756, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 5, 5]}, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=null, roundTripTimeNanos=940841}
2019-02-28 19:15:51.645  INFO 23556 --- [localhost:52756] org.mongodb.driver.cluster               : Discovered cluster type of STANDALONE
2019-02-28 19:15:51.880  INFO 23556 --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:52756], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-02-28 19:15:51.916  INFO 23556 --- [localhost:52756] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:52756

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$OpenCompletionHandler.failed(AsynchronousSocketChannelStream.java:272) ~[mongodb-driver-core-3.8.2.jar:na]
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:128) ~[na:1.8.0_131]
	at sun.nio.ch.Invoker$2.run(Invoker.java:218) ~[na:1.8.0_131]
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.io.IOException: 在一个非套接字上尝试了一个操作。
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl.connect0(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl.access$200(WindowsAsynchronousSocketChannelImpl.java:43) ~[na:1.8.0_131]
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl$ConnectTask.run(WindowsAsynchronousSocketChannelImpl.java:235) ~[na:1.8.0_131]
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl.implConnect(WindowsAsynchronousSocketChannelImpl.java:382) ~[na:1.8.0_131]
	at sun.nio.ch.AsynchronousSocketChannelImpl.connect(AsynchronousSocketChannelImpl.java:209) ~[na:1.8.0_131]
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream.openAsync(AsynchronousSocketChannelStream.java:86) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream.open(AsynchronousSocketChannelStream.java:67) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) ~[mongodb-driver-core-3.8.2.jar:na]
	... 1 common frames omitted

2019-02-28 19:15:52.211  INFO 23556 --- [           main] m.p.ReactiveMongoTemplateIntegrationTest : Started ReactiveMongoTemplateIntegrationTest in 4.324 seconds (JVM running for 5.29)
2019-02-28 19:15:52.415  INFO 23556 --- [           main] org.mongodb.driver.cluster               : No server chosen by com.mongodb.async.client.ClientSessionHelper$1@65d8dff8 from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=localhost:52756, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.io.IOException: 在一个非套接字上尝试了一个操作。}}]}. Waiting for 30000 ms before timing out
```

**Comment by hopefulwalker** [comment]
It's depressed。
I'm not sure what happen,something related to the windows version?
The same application, it works in other machine. even they connect to the same mongoDb.
It seems to be related to the platform. (JVM, OS...)
I have no idea to find the root cause....

**Comment by mp911de** [comment]
It can be possible that there's an IP stack issue. In any case, this issue isn't related to Spring Data examples so closing that one.
