### ISSUE TITLE
Run "Spring Data MongoDB - Transactions" model Error "java.io.IOException: Could not open inputStream"

### ISSUE THREAD

**Issue by derekzhan** [spring-projects/spring-data-examples#548]
```java
2019-12-31 12:03:25,462  INFO le.springdata.mongodb.util.EmbeddedMongo: 316 - Starting config servers at ports 27146,27159,27165
2019-12-31 12:03:25,466  INFO le.springdata.mongodb.util.EmbeddedMongo: 318 - Starting replica set 'rs0' servers at ports 27120,27126,27137
2019-12-31 12:03:27,603 ERROR flapdoodle.embed.process.runtime.Starter:  68 - prepare executable
java.io.IOException: Could not open inputStream for https://downloads.mongodb.org/win32/mongodb-win32-x86_64-ssl-3.7.9.zip
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:131)
	at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:69)
	at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:66)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.checkDistribution(ExtractedArtifactStore.java:60)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:56)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:49)
	at example.springdata.mongodb.util.MongosSystemForTestFactory.initializeReplicaSet(MongosSystemForTestFactory.java:111)
	at example.springdata.mongodb.util.MongosSystemForTestFactory.start(MongosSystemForTestFactory.java:82)
	at example.springdata.mongodb.util.EmbeddedMongo$ReplSet.doStart(EmbeddedMongo.java:321)
	at example.springdata.mongodb.util.EmbeddedMongo$ReplSet.start(EmbeddedMongo.java:299)
	at example.springdata.mongodb.util.EmbeddedMongo.before(EmbeddedMongo.java:188)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://downloads.mongodb.org/win32/mongodb-win32-x86_64-ssl-3.7.9.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:127)
	... 19 common frames omitted
2019-12-31 12:03:27,604 ERROR le.springdata.mongodb.util.EmbeddedMongo: 190 - Cannot start MongoDB
java.lang.RuntimeException:  Error while starting cluster. 
	at example.springdata.mongodb.util.EmbeddedMongo$ReplSet.doStart(EmbeddedMongo.java:326)
	at example.springdata.mongodb.util.EmbeddedMongo$ReplSet.start(EmbeddedMongo.java:299)
	at example.springdata.mongodb.util.EmbeddedMongo.before(EmbeddedMongo.java:188)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: de.flapdoodle.embed.process.exceptions.DistributionException: java.io.IOException: Could not open inputStream for https://downloads.mongodb.org/win32/mongodb-win32-x86_64-ssl-3.7.9.zip
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:69)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:49)
	at example.springdata.mongodb.util.MongosSystemForTestFactory.initializeReplicaSet(MongosSystemForTestFactory.java:111)
	at example.springdata.mongodb.util.MongosSystemForTestFactory.start(MongosSystemForTestFactory.java:82)
	at example.springdata.mongodb.util.EmbeddedMongo$ReplSet.doStart(EmbeddedMongo.java:321)
	... 11 common frames omitted
Caused by: java.io.IOException: Could not open inputStream for https://downloads.mongodb.org/win32/mongodb-win32-x86_64-ssl-3.7.9.zip
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:131)
	at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:69)
	at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:66)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.checkDistribution(ExtractedArtifactStore.java:60)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:56)
	... 15 common frames omitted
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://downloads.mongodb.org/win32/mongodb-win32-x86_64-ssl-3.7.9.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:127)
	... 19 common frames omitted

org.junit.AssumptionViolatedException: Cannot start MongoDB. Skipping

**Comment by derekzhan** [comment]
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/261
